const Action = {
  FETCHING_NEW: Symbol('FETCHING_NEW'),
  FETCH_NEW_SUCCEEDED: Symbol('FETCH_NEW_SUCCEEDED'),
  FETCH_NEW_FAILED: Symbol('FETCH_NEW_FAILED'),

  FETCHING_NEW_STORIES: Symbol('FETCHING_NEW_STORIES'),
  FETCH_NEW_STORIES_SUCCEEDED: Symbol('FETCH_NEW_STORIES_SUCCEEDED'),
  FETCH_NEW_STORIES_FAILED: Symbol('FETCH_NEW_STORIES_FAILED'),

  FETCHING_ITEM: Symbol('FETCHING_ITEM'),
  FETCH_ITEM_SUCCEEDED: Symbol('FETCH_ITEM_SUCCEEDED'),
  FETCH_ITEM_FAILED: Symbol('FETCH_ITEM_FAILED'),
};
Object.freeze(Action);

export default Action;
