const Action = {
  SWITCH_PAGE: Symbol('SWITCH_PAGE'),

  FETCHING_ITEM_LIST: Symbol('FETCHING_ITEM_LIST'),
  FETCH_ITEM_LIST_SUCCEEDED: Symbol('FETCH_ITEM_LIST_SUCCEEDED'),
  FETCH_ITEM_LIST_FAILED: Symbol('FETCH_ITEM_LIST_FAILED'),

  FETCHING_ITEMS: Symbol('FETCHING_ITEMS'),
  FETCH_ITEMS_SUCCEEDED: Symbol('FETCH_ITEMS_SUCCEEDED'),
  FETCH_ITEMS_FAILED: Symbol('FETCH_ITEMS_FAILED'),

  FETCHING_ITEM: Symbol('FETCHING_ITEM'),
  FETCH_ITEM_SUCCEEDED: Symbol('FETCH_ITEM_SUCCEEDED'),
  FETCH_ITEM_FAILED: Symbol('FETCH_ITEM_FAILED'),
};
Object.freeze(Action);

export default Action;
